---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certified
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certified
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certified
subjects:
  - kind: ServiceAccount
    name: certified
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: certified
  apiGroup: rbac.authorization.k8s.io